version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: skyshield_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: skyshield_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skyshield_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: skyshield_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skyshield_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgrespassword@db:5432/skyshield_db
      - REDIS_URL=redis://redis:6379/0
      - APP_ENV=DEVELOPMENT
      - DEMO_MODE=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  pgdata:
  redisdata:
